### ISSUE TITLE
Button to mark everything as "not fuzzy" doesn't work

### ISSUE THREAD

**Issue by EmilStenstrom** [mbi/django-rosetta#132]
When translating I often get lots of fuzzy matches. But the little [-] button next to the header the unmarks things as fuzzy doesn't work any more. I'm using Firefox 39 if that matters.

![skarmavbild 2015-06-04 kl 10 44 53](https://cloud.githubusercontent.com/assets/224130/7980329/cdb6d1d0-0aa6-11e5-8467-d563bd5b669c.png)

**Comment by mbi** [comment]
Thanks for reporting this, fixed in edfc1d40d37b7ec17f615177ded2a34fbbe5f1ca

**Comment by EmilStenstrom** [comment]
I still have this issue, using Rosetta 0.7.6. Could this be because no release have been done since then?

**Comment by mbi** [comment]
Hi. Indeed: these changes aren't in a point release yet, I'm waiting for Django 1.9 to be released to put out a new point release. In the meantime you could `pip install -e` the development version if you need these changes.
